### ISSUE TITLE
Added timer feature and (type only) input validation on pref param

### ISSUE THREAD

**Issue by gstarrett2** [bwynn/gallery#7]
Hi Brian - I'm using your code for a non-profit I support and thought I'd feed back to you a couple small tweaks I made to the JavaScript you have for the gallery.  The interval timer is active and auto scrolls the images until you manually change the image.

[Result.txt](https://github.com/bwynn/gallery/files/2312060/Result.txt)

**Comment by bwynn** [comment]
Hey @gstarrett2, thanks for letting me know and for the feedback!

I haven't maintained this library for quite some time, but if you'd like to create a pull request, I'd be happy to address/expose/update your `activeTimer` feature and bump the version 🙂
